const strinssss = 'VNIT NAGPUR_BT19CME104_SURAJSHELKE_10th PASSING CERTIFICATE';
const a = 'VNIT NAGPUR_BT19CME104_SURAJSHELKE_12th Marksheet/Passing certificate';
const b = 'VNIT NAGPUR_BT19CME104_SURAJSHELKE_PROVISIONAL GRADE CARD';

const e = 'VNIT NAGPUR_BT19CME104_SURAJSHELKE_23850';

const resume = 'VNIT NAGPUR_BT19CME104_SURAJSHELKE_RESUME'

